# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Login(object):
    def setupUi(self, Form_Login):
        Form_Login.setObjectName("Form_Login")
        Form_Login.resize(822, 589)
        Form_Login.setAutoFillBackground(False)
        Form_Login.setStyleSheet("#Form_Login {\n"
"    border-image: url(:/resources/images/background.png);\n"
"}")
        self.btn_login = QtWidgets.QPushButton(Form_Login)
        self.btn_login.setGeometry(QtCore.QRect(270, 460, 91, 31))
        self.btn_login.setStyleSheet("border-image: url(:/resources/images/load_1.jpg);")
        self.btn_login.setText("")
        self.btn_login.setObjectName("btn_login")
        self.bt_quit = QtWidgets.QPushButton(Form_Login)
        self.bt_quit.setGeometry(QtCore.QRect(500, 460, 91, 31))
        self.bt_quit.setStyleSheet("border-image: url(:/resources/images/close_1.jpg);")
        self.bt_quit.setText("")
        self.bt_quit.setObjectName("bt_quit")
        self.le_user_info = QtWidgets.QLineEdit(Form_Login)
        self.le_user_info.setGeometry(QtCore.QRect(370, 300, 141, 31))
        self.le_user_info.setObjectName("le_user_info")
        self.le_pwd_info = QtWidgets.QLineEdit(Form_Login)
        self.le_pwd_info.setGeometry(QtCore.QRect(370, 360, 141, 31))
        self.le_pwd_info.setObjectName("le_pwd_info")
        self.label = QtWidgets.QLabel(Form_Login)
        self.label.setGeometry(QtCore.QRect(220, 90, 501, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"楷体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_Login)
        self.label_2.setGeometry(QtCore.QRect(340, 190, 231, 31))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"楷体\";")
        self.label_2.setObjectName("label_2")
        self.label_user_icon = QtWidgets.QLabel(Form_Login)
        self.label_user_icon.setGeometry(QtCore.QRect(300, 300, 41, 31))
        self.label_user_icon.setStyleSheet("border-image: url(:/resources/images/user.png);")
        self.label_user_icon.setText("")
        self.label_user_icon.setObjectName("label_user_icon")
        self.label_pwd_icon = QtWidgets.QLabel(Form_Login)
        self.label_pwd_icon.setGeometry(QtCore.QRect(300, 360, 41, 31))
        self.label_pwd_icon.setStyleSheet("border-image: url(:/resources/images/pwd.png);")
        self.label_pwd_icon.setText("")
        self.label_pwd_icon.setObjectName("label_pwd_icon")

        self.retranslateUi(Form_Login)
        QtCore.QMetaObject.connectSlotsByName(Form_Login)

    def retranslateUi(self, Form_Login):
        _translate = QtCore.QCoreApplication.translate
        Form_Login.setWindowTitle(_translate("Form_Login", "卫星检测系统"))
        self.label.setText(_translate("Form_Login", "Satellite detection platform"))
        self.label_2.setText(_translate("Form_Login", "卫星检测平台"))
import apprcc_rc
